name: "CITests"

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  citests:
    name: CI-Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          submodules: 'recursive'

      - name: Install DPDK dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libnuma-dev meson ninja-build pkg-config python3-pip

      - name: Install Python dependencies for DPDK
        run: |
          pip3 install pyelftools

      - name: Install DPDK 21.11
        run: |
          wget https://fast.dpdk.org/rel/dpdk-21.11.9.tar.xz
          tar xf dpdk-21.11.9.tar.xz
          cd dpdk-stable-21.11.9
          meson build
          ninja -C build
          sudo ninja -C build install
          sudo ldconfig

      - name: Build picoquic
        run: |
          ./ci/build_picotls.sh
          export PKG_CONFIG_PATH=/usr/local/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH
          cmake .
          make

      - name: Perform Unit Tests
        run: |
          ulimit -c unlimited -S
          ./picoquic_ct -n -r && QUICRESULT=$?
          ./picohttp_ct -n -r -x http_corrupt && HTTPRESULT=$?
          if [[ ${QUICRESULT} == 0 ]] && [[ ${HTTPRESULT} == 0 ]]; then exit 0; fi;
          exit 1